import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import Sidebar from '../components/sidebar'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grant Bounty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>
      
      
      <main className={styles.main}>
        <Masthead/>
        
      </main>

      
    </div>
  )
}

export default Home
